### ISSUE TITLE
Delete mention

### ISSUE THREAD

**Issue by SalvatoreAD** [magicmon/Mentions#1]
Can you completely delete the mention when you press it back?

**Comment by magicmon** [comment]
umm... I will try adding that item.

**Comment by ashwinshres** [comment]
In MentionTextView:

`public func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {`

just update it to:


`public func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        replaceValues = (textView.text, range, text)
        if let firstIndex = highlightUsers.firstIndex(where: { (aa) -> Bool in
            return aa.1.contains(range.location)
        }) {
            self.text = self.text.replacing("", range: highlightUsers[firstIndex].1)
            highlightUsers.remove(at: firstIndex)
            return false
        }
        return true
    }`

and you are good to go @SalvatoreAD

**Comment by magicmon** [comment]
@ashwinshres thank you for sample code. I will modify it for your code. and will update soon...

**Comment by magicmon** [comment]
released 1.0.1 version.
(append MentionDeleteType)

[use]
mentionTextView.deleteType = .cancel or .delete

if you want completely delete the mention, use the MentionDeleteType.delete
