### ISSUE TITLE
HyperLink/ Links

### ISSUE THREAD

**Issue by CodeWithBikramjeet** [magicmon/Mentions#2]
Hello Team, Can you tell me how I can show http://www.goole.com/ as like UITextView. Unable to showing http://www.goole.com/ as like UITextView.

**Comment by magicmon** [comment]
@Bikram786 
I have identified an issue with converting HTML into mentions. I will soon release an updated version to fix this problem. Thank you for reporting it.

**Comment by CodeWithBikramjeet** [comment]
@magicmon thanks for your response. Can you tell me how much it will take.

**Comment by CodeWithBikramjeet** [comment]
There is one more problem when i used the MentionTextView. Plz check in attached files. 
![Simulator Screen Shot - iPhone 14 - 2023-07-11 at 12 53 03](https://github.com/magicmon/Mentions/assets/29310008/47137493-958e-48a2-9860-428e145d4643)

![Simulator Screen Shot - iPhone 14 - 2023-07-11 at 12 53 09](https://github.com/magicmon/Mentions/assets/29310008/650c90c3-c737-44cc-a9d2-ef2a0578dd31)

**Comment by magicmon** [comment]
hmm... 
I think it will take about a week to check and fix bugs.
I'll let you know if I fix it before then.

**Comment by CodeWithBikramjeet** [comment]
Ok @magicmon. Thanks for your response.

**Comment by magicmon** [comment]
@Bikram786 
Version[ 1.1.0](https://github.com/magicmon/Mentions/releases/tag/1.1.0) was released.
It is implemented to choose between "mention" and "html".
```
textLabel.pattern = .mention
or
textLabel.pattern = .html
```

If you want to support both, it will take a little more time.

**Comment by CodeWithBikramjeet** [comment]
@magicmon Please first release this how I can show http://www.goole.com/ as like UITextView. Unable to showing http://www.goole.com/ as like UITextView. After that you can release other one.

**Comment by magicmon** [comment]
@Bikram786 
I'm sorry, I think I understood it differently.
Is the part you mentioned the one squared in the photo?
If not, please send me a screenshot or video and I'll check it out.

<img width="425" alt="스크린샷 2023-07-13 오전 1 27 50" src="https://github.com/magicmon/Mentions/assets/1018447/5604c106-fd26-4531-89f5-5c4a37ac61c2">

**Comment by CodeWithBikramjeet** [comment]
@magicmon Plz check this screenshot hope you understand. 

![Simulator Screen Shot - iPhone 14 - 2023-07-12 at 22 01 24](https://github.com/magicmon/Mentions/assets/29310008/24d6952e-fb54-4c6f-bf2b-c5b2f96db927)

![Simulator Screen Shot - iPhone 14 - 2023-07-12 at 22 05 17](https://github.com/magicmon/Mentions/assets/29310008/e5d18a51-c211-435a-a7a1-08839202fd18)

**Comment by magicmon** [comment]
@Bikram786 
I'm sorry, I don't know how you're using our library, so I might not have caught what you want. 
I wonder if **MentionLabel** needs it to be clickable. Or is it **MentionTextView**?



https://github.com/magicmon/Mentions/assets/1018447/074b9334-4392-431a-ba51-b5e042c822e6

![Simulator Screenshot - iPhone 14 Pro - 2023-07-13 at 23 00 27](https://github.com/magicmon/Mentions/assets/1018447/e3054959-5442-483e-a105-251a8fea2e28)

**Comment by magicmon** [comment]
If you tell us whether the chat message UI is **MentionLabel,** **MentionTextView** or **UITextView**, it will be very helpful in solving it.

**Comment by CodeWithBikramjeet** [comment]
@magicmon Thanks alot for your quick message. Chat message UI will be both type. It can be MentionLabel as well as MentionTextView. and I want functionality like normal UItextView. If you seen and user enter a normal www.google.com text and UItextView automatically convert this www.google.com  into link type. And when user click on this link it automatically redirect according. Hope you understand.

**Comment by magicmon** [comment]
@Bikram786 
Version 1.1.1 was released.
It doesn't seem easy to provide the same as **UITextView**. However, I tried adding a few features to make the hyperlink work as much as possible.
and added **ParserPattern.allText**.
some examples.

// How to use in MentionTextView
```
mentionTextView.setMentionText("www.google.com and [magicmon]",
                               pattern: .mention,
                               prefixMention: "@")
mentionTextView.deleteType = .cancel // or .delete
mentionTextView.isEditable = false
mentionTextView.dataDetectorTypes = [.link]
```

// How to use in MentionLabel
```
textLabel.setMentionText("[www.google.com] or [@magicmon]",
                                 pattern: .allText, // **important**
                                 prefixMention: "")
```

https://github.com/magicmon/Mentions/assets/1018447/43943447-3a55-4ee7-8305-d4290fa31b76


![Simulator Screenshot - iPhone 14 Pro - 2023-07-14 at 00 06 49](https://github.com/magicmon/Mentions/assets/1018447/788136ee-bc8e-44db-8bc9-f9f387597572)

**Comment by CodeWithBikramjeet** [comment]
@magicmon ok let me check and update you accordingly. Thanks for your support. But about below  query. It comes that time suppose you add a mention tag in MentionTextView and when user delete the mention tag  one by one and again user write any other text in between mention that time text color showing according to mention text.

<img width="1512" alt="Screenshot 2023-07-13 at 8 53 25 PM" src="https://github.com/magicmon/Mentions/assets/29310008/07d4fa85-f0d3-4479-a965-9d173c20076e">

**Comment by magicmon** [comment]
@Bikram786 
I think I know what it's about. 
But it seems to work well in the sample.
Can you attach the tested video?

https://github.com/magicmon/Mentions/assets/1018447/cc33f28e-74f8-41c0-8ef7-e80833656618

**Comment by CodeWithBikramjeet** [comment]
@magicmon, when I updated my pod with Version 1.1.1 and try to implement update code and got error 

<img width="693" alt="Screenshot 2023-07-13 at 9 25 26 PM" src="https://github.com/magicmon/Mentions/assets/29310008/4e396311-858b-4a35-b5ac-3a41f1237f93">

**Comment by magicmon** [comment]
@Bikram786 
Sorry...😂😂😂
Updated to version 1.1.2.
