### ISSUE TITLE
Mentions are not updating when text cut operation is performed.

### ISSUE THREAD

**Issue by ShivamSinghal11** [magicmon/Mentions#4]
Hello there!
Whenever we select any text from MentionTextView and perform a cut operation then the previously selected mention disappears or it was showing in regular black color. also when we press the back button then it works fine.

Please check the video for more information.

https://github.com/magicmon/Mentions/assets/96857421/622cc634-11cd-4fb2-98e4-f05393f98f5b

How can we fix this issue? please suggest.

**Comment by magicmon** [comment]
@ShivamSinghal11 
Hello, this is magicmon. It was confirmed that the issue occurs when deleting the first word. We will soon be able to deploy a fix version.

**Comment by ShivamSinghal11** [comment]
Hello Magicmon,
Do you have any update on the above issue?

**Comment by ShivamSinghal11** [comment]
Hello Magicmon,
Is there any update on the fixed version build for the above issue mentioned.

**Comment by magicmon** [comment]
@ShivamSinghal11 
Sorry for the delay due to personal reasons. I will fix it as soon as possible and let you know.

**Comment by magicmon** [comment]
Hello @ShivamSinghal11 
I've made the changes you mentioned and deployed version 1.1.3. Please check it out.
